My_Second_Project/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from Login_app import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name="logout"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls')),
]

My_Second_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User


# username, password, email

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)


    def __str__(self):
        return self.user.username

My_Second_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')




class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ("facebook_id", "profile_pic")

My_Second_Project/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm, UserInfoForm
from Login_app.forms import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.


def login_page(request):
    return render(request, 'Login_app/login.html', context={})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print("Login Successfull!")
                return HttpResponseRedirect(reverse('Login_app:index'))

            else:
                return HttpResponse("Account is not active!!")

        else:
            return HttpResponse("Login Details are Wrong!")

    else:
        return HttpResponseRedirect(reverse('Login_app:login'))


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))


def index(request):
    dict={}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict = {'user_basic_info':user_basic_info, 'user_more_info':user_more_info}
    return render(request, 'Login_app/index.html', context=dict)


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()

            registered = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()


    dict = {'user_form':user_form, 'user_info_form':user_info_form, 'registered':registered}
    return render(request, 'Login_app/register.html', context=dict)

My_Second_Project/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
   <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Login_app:index' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
      <li>
        <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
      </li>
      {% else %}
      <li>
        <a class="nav-link" href="{% url 'Login_app:register' %}">Register</a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  <div class="container" style="padding-top:20px">
    {% block body_block %}
    {% endblock %}
  </div>
  </body>
</html>

My_Second_Project/templates/Login_app/index.html
{% extends 'Login_app/base.html' %}
{% block body_block %}
{% if user.is_authenticated %}
<p>Hi {{ user_basic_info.username }},</p>
<p>Your Email: {{ user_basic_info.email }}</p>
<p><a href="{{ user_more_info.facebook_id }}">Facebook Profile</a></p>
<img src="/media/{{ user_more_info.profile_pic }}" width="200px">
{% else %}
<div class='alert alert-primary'>You are not logged in!</div>
{% endif %}
{% endblock %}

My_Second_Project/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}
{% block body_block %}
<h3>Please Login</h3>
<form action="{% url 'Login_app:user_login' %}" method="POST">
  <label for="username">Username: </label>
  <input type="text" name="username" placeholder="Enter Username.." required class="form-control">
  <br>
  <label for="password">Password: </label>
  <input type="password" name="password" placeholder="Enter Password.." required class="form-control">
  <br>
  {% csrf_token %}
  <input type="submit" name="submit" value="Login" class="btn btn-info btn-sm">
</form>
{% endblock %}

My_Second_Project/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load staticfiles %}
{% block body_block %}
{% if registered %}
<div class="alert alert-success">Congratulations! Registration Successfull</div>
{% else %}
<form enctype="multipart/form-data" method="POST">
  {{ user_form.as_p }}
  {{ user_info_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Register">
</form>
{% endif %}

{% endblock %}